# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Winter Workshop on Complex Systems 2020
email: wwcs2020@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The Winter Workshop on Complex Systems is a one-week workshop where young researchers from all over the world
  gather together for discussing about complexity science and engaging into novel research projects.
  This is the 6th edition of the WWCS and will be held in Switzerland.
  Previously it was held in Brussels, Madrid and Petnica, Utrecht and Zakopane.
tagline: 27 January -- 31 January 2020 Switzerland
#baseurl: "_site" # the subpath of your site, e.g. /blog
#twitter_username: winter_complex
github_username:  wwcs2020

# Build settings
markdown: kramdown
theme: jekyll-theme-hydejack

menu:
  - title: Home
    url:   /index/
  - title: Programme
    url:   /programme/
  - title: Speakers
    url:   /speakers/
  - title: Venue
    url:   /venue/
  - title: Registration
    url: /registration/
  - title: Contacts
    url:   /contacts/
  - title: Application
    url:   /application/
  - title: Sponsors
    url:   /sponsors/

#layout: list

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-avatar
  - jemoji


#pagination:
#  enabled: true
#  per_page: 5
#  title: ':title - page :num'
#  permalink: '/page/:num/'
#  sort_reverse: true
logo: assets/icons/icon@3x.png #https://github.com/qwtel/hydejack/blob/master/_config.yml

accent_image: /assets/image/swissbg.jpg
accent_color: rgb(79,177,186)




# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

compress_html:
  comments:  ["<!-- ", " -->"]
  clippings: all
  endings:   all

sass:
  style:     compressed
